export type Competency = "focus" | "judgment" | "communication" | "delegation" | "commitments" | "self_awareness";
export type Evidence = { meeting_id: string; meeting_title: string; recorded_at: string | null; quote: string; start: number | null; speaker: string | null; self_attributed: boolean; chunk_index: number; source_hash: string };
export type Observation = { competency: Competency; observation: string; hypothesis: string; alternative: string; experiment: string; evidence: Evidence[] };
export type MemoryLifecycle = "active" | "paused" | "completed" | "superseded";
export type MemoryVersion = { content: string; status: string; at: string; lifecycle?: MemoryLifecycle; valid_from?: string; valid_until?: string | null; evidence?: Evidence[]; origin?: "legacy" | "user" | "inferred"; supersedes_id?: string | null };
export type CoachProfile = { user_id: string; enabled: boolean; weekly_enabled: boolean; morning_enabled?: boolean; evening_enabled?: boolean; nudges_enabled?: boolean; morning_hour?: number; evening_hour?: number; goals: string; context: string; timezone: string; review_day: number; review_hour: number; revision: number; last_run_at: string | null; last_error: string | null; created_at: string; updated_at: string };
export type CoachMemory = { id: string; user_id: string; kind: "goal" | "context" | "pattern" | "experiment"; content: string; status: "hypothesis" | "confirmed" | "rejected"; stale?: boolean; lifecycle?: MemoryLifecycle; valid_from?: string; valid_until?: string | null; supersedes_id?: string | null; origin?: "legacy" | "user" | "inferred"; goal_area?: "work" | "life" | null; goal_due?: string | null; goal_measure?: string | null; evidence: Evidence[]; history: MemoryVersion[]; created_at: string; updated_at: string };
export type ReportPeriodSource = { from:string; to:string; fingerprint:string };
export type ReportSource = { meeting_id:string; context_hash:string };
export type CoachMessage = { context_periods?:ReportPeriodSource[]; context_version?:number|null; context_sources?:ReportSource[]; context_freshness?:"current"|"unknown"|"stale"; id: string; role: "user" | "assistant"; content: string; evidence: Evidence[]; stale?: boolean; idempotency_key?: string | null; created_at: string };
export type ReviewContent = { accountability_fingerprint?:string; context_version?:number; context_periods?:ReportPeriodSource[]; context_sources?:ReportSource[]; report_context?:ReportPeriodSource; headline: string; focus: string; observations: Observation[]; progress: string; experiment: string; question: string; limitations: string[] };
export type CoachReview = { id: string; week_start: string; content: ReviewContent; model: string; profile_revision?: number; stale?: boolean; created_at: string };
export type CoachAnalysis = { id: string; meeting_id: string; source_hash: string; chunk_index: number; chunk_count: number; observations: Observation[]; summary: string; model: string; created_at: string };
export type CoachMeeting = { summary?:string|null; executive_summary?:string|null; id: string; nome: string | null; original_filename: string; recorded_at: string | null; transcription: string; segments: { speaker: string; start: number; end: number; text: string }[] | null; speaker_labels: Record<string,string> | null; speaker_pessoas: Record<string,string> | null };
export type Coverage = { report_ready_meetings?:number; executive_report_meetings?:number; summary_only_meetings?:number; missing_report_meetings?:number; total_meetings: number; analyzed_meetings: number; analyzed_chunks: number; pending_meetings: number };
export type CoachState = { profile: CoachProfile; memories: CoachMemory[]; messages: CoachMessage[]; reviews: CoachReview[]; coverage: Coverage; model_available: boolean; model?:{provider:string;model:string;reviewer_model:string|null;semantic_enabled:boolean}; commitments?:CoachCommitment[] };

export type CoachCommitment = { id:string; user_id:string; tarefa_id:string|null; source_message_id:string|null; idempotency_key:string; title:string; status:"open"|"completed"|"renegotiated"|"cancelled"|"unknown"; outcome:string|null; outcome_source:"user_report"|"task_record"|"unknown"; due_at:string|null; history:{status:string;outcome:string|null;at:string;source_message_id?:string;reported_outcome?:string}[]; created_at:string; updated_at:string; task_status?:string|null; task_completed_at?:string|null; task_updated_at?:string|null };

/** Revision captured by the same transaction that writes or replays a commitment. */
export type CoachCommitmentReceipt = CoachCommitment & {profile_revision:number};
