import { ArrowUpRight } from "lucide-react";
import { competencies } from "./shared";

const sources = [
  { title: "Stanford Leadership Institute — modelo de 2026", url: "https://www.gsb.stanford.edu/experience/about/leadership/updates/introducing-stanford-leadership-institute", original: "Cinco capacidades: autoconhecimento, consideração de outras perspectivas, comunicação integral, tomada de decisão e compreensão do contexto.", adaptation: "Apoiar reflexão sobre dificuldades, escolhas e contexto. O acompanhamento dos seus combinados é uma função própria do Ações." },
  { title: "Stanford LEAD", url: "https://www.gsb.stanford.edu/exec-ed/programs/stanford-lead/curriculum/courses", original: "Cursos de pensamento analítico, estratégia, decisões e comunicação.", adaptation: "Perguntas sobre o problema, as alternativas e o resultado de uma decisão." },
  { title: "Intentional Leadership: A 360 Approach", url: "https://www.gsb.stanford.edu/exec-ed/programs/stanford-lead/curriculum/courses/intentional-leadership", original: "Feedback 360 e planejamento do desenvolvimento pessoal.", adaptation: "Refletir sobre seus objetivos e dificuldades. O coach não coleta nem simula avaliação 360." },
  { title: "Leadership Labs", url: "https://www.gsb.stanford.edu/experience/learning/leadership/labs", original: "Exercícios de equipe e reflexão sobre decisões em situações de ambiguidade.", adaptation: "Aprender com escolhas e tentativas que você trouxer, ajustando o próximo passo ao seu objetivo." },
  { title: "Interpersonal Dynamics", url: "https://www.gsb.stanford.edu/experience/learning/leadership/interpersonal-dynamics", original: "Aprendizagem experiencial sobre relações, comunicação e impacto sobre outras pessoas.", adaptation: "Conversar sobre dificuldades de comunicação quando você pedir, sem presumir como o time percebe sua liderança." },
  { title: "Arbuckle Leadership Fellows", url: "https://www.gsb.stanford.edu/experience/learning/leadership/arbuckle-leadership-fellows-program", original: "Desenvolver outras pessoas por coaching, facilitação e mentoria.", adaptation: "Ajudar você a decidir e avançar com autonomia, orientando sem assumir suas decisões." },
  { title: "Cardinal at Work — Competencies", url: "https://cardinalatwork.stanford.edu/careers/performance-management/performance-management/competencies", original: "A Stanford publica o Leadership Architect, de autoria da Korn Ferry: 38 competências em Thought, Results, People e Self.", adaptation: "Referência complementar aos seis eixos próprios do Ações, sem testes ou escalas de competência." },
  { title: "Stanford LEAP", url: "https://leap360.stanford.edu/home", original: "Ciclo de feedback, plano de desenvolvimento, acompanhamento e reavaliação.", adaptation: "Objetivos, memória revisável e acompanhamento dos combinados aceitos por você." },
  { title: "LEAP — Acompanhamento", url: "https://leap360.stanford.edu/step4", original: "Diário de progresso e aprendizagem com lembrete semanal.", adaptation: "Revisitar combinados, avanços e dificuldades, com uma próxima ação possível." },
  { title: "LEAP — Avaliação 360", url: "https://leap360.stanford.edu/step1", original: "Autoavaliação e avaliações de gestores, pares e liderados.", adaptation: "Delimitar o que este coach não oferece: percepção do time e avaliações por gestores, pares ou liderados." },
];

const questions = ["O que merece atenção e o que pode esperar?", "Qual critério sustenta esta escolha?", "Quando você pedir: o que precisa esclarecer para avançar?", "O que depende de você e o que depende de outra pessoa?", "O que ficou combinado e como foi a tentativa?", "Qual dificuldade apareceu e o que ajuda na próxima tentativa?"];

export function ReferencesView() {
  return (
    <div className="space-y-7">
      <header><h2 className="font-display text-2xl">De onde vem esta abordagem</h2><p className="mt-2 text-sm leading-relaxed text-muted-strong">Seu coach ajuda a priorizar, entender dificuldades, retomar combinados e ajustar o próximo passo. Fontes públicas de Stanford apoiam a reflexão; o acompanhamento pessoal é uma adaptação do Ações, sem avaliação ou certificação da universidade.</p></header>
      <section><h3 className="text-sm font-semibold">Seis eixos do Ações</h3><p className="mt-1 text-xs leading-relaxed text-muted-strong">As cinco capacidades do Stanford Leadership Institute ajudam principalmente no autoconhecimento, nas decisões e na leitura de contexto. Os seis eixos abaixo organizam a abordagem do Ações; não são uma escala de avaliação nem um roteiro obrigatório.</p><div className="mt-4 grid gap-x-6 gap-y-4 sm:grid-cols-2">{Object.entries(competencies).map(([key, title], index) => <div key={key} className="border-l-2 border-border pl-3"><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs leading-relaxed text-muted-strong">{questions[index]}</p></div>)}</div></section>
      <section><h3 className="mb-3 text-sm font-semibold">Material original e como foi adaptado</h3><div className="divide-y divide-border">{sources.map((source) => <details key={source.url} className="group py-2"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-3 text-sm font-medium focus-visible:outline-2 focus-visible:outline-offset-2"><span>{source.title}</span><span className="text-xs font-normal text-muted-strong group-open:hidden">Ver</span></summary><dl className="space-y-3 pb-4 pt-2 text-sm leading-relaxed"><div><dt className="text-xs font-semibold text-muted-strong">Na fonte original</dt><dd className="mt-1">{source.original}</dd></div><div><dt className="text-xs font-semibold text-[var(--calm)]">Adaptação no Ações</dt><dd className="mt-1">{source.adaptation}</dd></div></dl><a href={source.url} target="_blank" rel="noopener noreferrer" className="mb-3 inline-flex min-h-9 items-center gap-1 text-xs text-[var(--calm)] underline underline-offset-4">Ler a fonte original <ArrowUpRight size={13} aria-hidden="true" /><span className="sr-only"> (abre em nova aba)</span></a></details>)}</div></section>
      <section className="rounded-xl bg-accent p-4 text-sm leading-relaxed"><h3 className="font-semibold">Franqueza com evidência, sem notas artificiais</h3><p className="mt-2 text-muted-strong">Um episódio não define quem você é. O coach deve separar registro de hipótese, considerar outras explicações e aceitar correções. Não mede personalidade, reputação ou competência com uma nota de 0 a 100.</p></section>
      <p className="text-[11px] leading-relaxed text-muted-strong">Fontes consultadas em 20 e 21 de setembro de 2026. Algumas páginas da GSB foram consultadas pelo índice oficial de busca. Nenhum material fechado de curso foi reproduzido.</p>
    </div>
  );
}
